---
# App settings
app:
  global:
    image: wger/server:latest
    imagePullPolicy: Always
    annotations: {}
    replicas: 1
  persistence:
    enabled: false
    storageClass: null
    accessModes:
      - ReadWriteMany
    size: 8Gi
    annotations: {}
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  environment:
    - name: TIME_ZONE
      value: UTC
    - name: ENABLE_EMAIL
      value: "False"
    - name: EMAIL_BACKEND
      value: "django.core.mail.backends.console.EmailBackend"
    - name: EMAIL_HOST
      value: None
    - name: EMAIL_PORT
      value: 587
    - name: EMAIL_HOST_USER
      value: None
    - name: EMAIL_HOST_PASSWORD
      value: None
    - name: FROM_EMAIL
      value: test@test.com

ingress:
  enabled: false
  url: fit.example.com
  tls: true
  annotations: {}
    
service:
  annotations: {}
  type: ClusterIP
  port: 8000

# PostgreSQL Settings. Only the bare minimum has been specified below.
# For more options, see https://github.com/bitnami/charts/tree/master/bitnami/postgresql
postgresql:
  # Note: keep these variables present as the chart uses them for the Deployment
  global:
    postgresql:
      auth:
        database: wger
        username: wger
        password: wger
      service:
        ports:
          postgresql: 5432
    persistence:
      enabled: true
      mountPath: /bitnami/postgresql
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 8Gi

# Redis Settings. Only the bare minimum has been specified below.
# For more options, see https://github.com/bitnami/charts/tree/master/bitnami/redis
redis:
  # Note: keep these variables present as the chart uses them for the Deployment
  auth:
    password: wger
    enabled: false
    sentinel: true
  master:
    containerPort: 6379
    persistence:
      enabled: false
      path: /data
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 8Gi
